require("lazy").setup({
	require("plugins.guess-indent"),
	require("plugins.gitsigns"),
	require("plugins.which-key"),
	require("plugins.telescope"),
	require("plugins.lazydev"),
	require("plugins.lspconfig"),
	require("plugins.conform"),
	require("plugins.blink"),
	require("plugins.tokyonight"),
	require("plugins.todo-comments"),
	require("plugins.mini"),
	require("plugins.treesitter"),
	require("plugins.smart-splits"),
	require("plugins.autopairs"),
	require("plugins.debug"),
	require("plugins.indent-blankline"),
	require("plugins.neo-tree"),
	require("plugins.undotree"),
}, {
	ui = {
		icons = vim.g.have_nerd_font and {} or {
			cmd = "⌘",
			config = "🛠",
			event = "📅",
			ft = "📂",
			init = "⚙",
			keys = "🗝",
			plugin = "🔌",
			runtime = "💻",
			require = "🌙",
			source = "📄",
			start = "🚀",
			task = "📌",
			lazy = "💤 ",
		},
	},
})
